# Pandas Level 1

In [35]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in /Users/w.ishal27/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/w.ishal27/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
pip help

Usage:
  /usr/local/bin/python3 -m pip <command> [options]

Commands:
  install                     Install packages.
  lock                        Generate a lock file.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible
dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package
indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the
                              main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment;
                              exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --keyring-provider <keyring_provider>
                              Enable the credential lookup via the keyring
                              library if user input is allowed. Specify which
                              mechanism to use [auto, disabled, import,
                              subprocess]. (default: auto)
  --proxy <proxy>             Specify a proxy in the form
                              scheme://[user:passwd@]proxy.server:port.
  --no-proxy-env              Do not read proxy configuration from environment
                              variables.
  --retries <retries>         Maximum attempts to establish a new HTTP
                              connection. (default: 5)
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-
                              index.
  --no-color                  Suppress colored output.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.
  --resume-retries <resume_retries>
                              Maximum attempts to resume or restart an
                              incomplete download. (default: 5)
Note: you may need to restart the kernel to use updated packages.

In [37]:
pip list

Package                 Version
----------------------- -----------
appnope                 1.0.0
asttokens               3.0.2
comm                    0.2.3
debugpy                 1.8.22
et_xmlfile              2.0.0
executing               2.2.1
ipykernel               7.3.0
ipython                 9.17.1
ipython_pygments_lexers 1.1.1
jedi                    0.20.0
jupyter_client          8.10.0
jupyter_core            5.9.1
matplotlib-inline       0.2.2
nest-asyncio2           1.7.3
numpy                   2.5.4
openpyxl                3.1.5
packaging               26.3
pandas                  3.1.0
parso                   0.8.7
pexpect                 4.9.0
pip                     26.2.2
platformdirs            4.12.1
prompt_toolkit          3.0.53
psutil                  7.2.2
ptyprocess              0.7.0
pure_eval               0.2.4
Pygments                2.21.0
python-dateutil         2.9.0.post0
pyzmq                   27.2.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.10
traitlets               5.16.1
typing_extensions       4.16.0
wcwidth                 0.9.1
Note: you may need to restart the kernel to use updated packages.

In [38]:
#Pass either list or tupple 

import pandas as pd 
Data_01 = (1,2,3,4,5)
Series = pd.Series(Data_01)
Series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [39]:
# Example of series using dictonary
Data_01 = { "KEY_1":1, "KEY_2":2, "KEY_3":3 }
Data_01
pd.Series(Data_01)

KEY_1    1
KEY_2    2
KEY_3    3
dtype: int64

In [40]:
New_Dict = {
    'Name': ['Wishal', 'Mohit', 'Sachin'],
    'Age': [17, 30, 40],
    'Education': ['12th', 'BBA', 'MBA']
}

df = pd.DataFrame(New_Dict)
df

     Name  Age Education
0  Wishal   17      12th
1   Mohit   30       BBA
2  Sachin   40       MBA

In [41]:
New_List = [["Wishal",17,"12Th"],
            ["Mohit", 20,"BBA"],
            ["Sachin",30,"MBA"]]

pd.DataFrame(New_List, columns=["Names", "Age", "Education"])

    Names  Age Education
0  Wishal   17      12Th
1   Mohit   20       BBA
2  Sachin   30       MBA

In [42]:
# Create Dataframe from Dictionary

file_path = "/Users/w.ishal27/Downloads/Small Airline.csv"

# Use the file path already defined in the notebook
df = pd.read_csv("/Users/w.ishal27/Desktop/EthansX/Small Airline.csv")
df

,Unnamed: 0,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [43]:

# Create Dataframe from Dictionary

file_path = "/Users/w.ishal27/Desktop/EthansX/Small Airline.csv"

df = pd.read_csv(file_path)
df

,Unnamed: 0,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [44]:

df = pd.read_excel("/Users/w.ishal27/Desktop/EthansX/file.xlsx")
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [45]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
df.to_csv("/Users/w.ishal27/Desktop/EthansX/Small Airline.csv")

In [47]:
df.describe

<bound method DataFrame.describe of    First_name Last_name   Age       City            Airline Date_of_Journey  \
0         Ram     Kumar  42.0  BANGALURU             IndiGo      2019-03-24
1       Mohan    Sharma  52.0    CHENNAI          Air India      2019-05-01
2        Tina       Ali  36.0       Pune        Jet Airways      2019-06-09
3       Jeetu    Gandhi   NaN      Delhi             IndiGo      2019-05-12
4       Meera    Kumari   NaN    LUCKNOW             IndiGo      2019-03-01
5         Ram     Kumar  42.0  BANGALURU                NaN      2019-03-24
6       Mohan    Sharma  52.0    CHENNAI                NaN      2019-05-01
7      Rajesh     Pawar  39.0        NaN        Jet Airways      2019-03-01
8      Sanjay     Patil  43.0        NaN        Jet Airways      2019-03-12
9     Trishul    Shinde  45.0       Pune  Multiple carriers      2019-05-27
10     Sameer     Patil  39.0      Delhi        Jet Airways      2019-03-12
11       Amol     Mahul  40.0    LUCKNOW        Jet Airways      2019-03-01
12    Praveen    Gurjar  47.0  BANGALURU        Jet Airways      2019-03-12
13     Sunita     Patil  40.0    CHENNAI  Multiple carriers      2019-05-27
14       Amol     Mahul  40.0    LUCKNOW        Jet Airways      2019-03-01
15    Praveen    Gurjar  47.0  BANGALURU        Jet Airways      2019-03-12
16     Sunita     Patil  40.0    CHENNAI  Multiple carriers      2019-05-27

    Dep_Time Arrival_Time  Dept_Hour  Dept_Minute  Arrival_Hour  \
0   22:20:00     01:10:00         22           20             1
1   05:50:00     13:15:00          5           50            13
2   09:25:00     04:25:00          9           25             4
3   18:05:00     23:30:00         18            5            23
4   16:50:00     21:35:00         16           50            21
5   22:20:00     01:10:00         22           20             1
6   05:50:00     13:15:00          5           50            13
7   05:05:00     08:00:00          5            5             8
8   08:55:00     10:25:00          8           55            10
9   11:25:00     19:15:00         11           25            19
10  10:25:00     18:55:00         10           25            18
11  05:05:00     08:00:00          5            5             8
12  08:55:00     10:25:00          8           55            10
13  11:25:00     19:15:00         11           25            19
14  05:05:00     08:00:00          5            5             8
15  08:55:00     10:25:00          8           55            10
16  11:25:00     19:15:00         11           25            19

    Arrival_Minute       Full Name
0               10       Ram-Kumar
1               15    Mohan-Sharma
2               25        Tina-Ali
3               30    Jeetu-Gandhi
4               35    Meera-Kumari
5               10       Ram-Kumar
6               15    Mohan-Sharma
7                0    Rajesh-Pawar
8               25    Sanjay-Patil
9               15  Trishul-Shinde
10              55    Sameer-Patil
11               0      Amol-Mahul
12              25  Praveen-Gurjar
13              15    Sunita-Patil
14               0      Amol-Mahul
15              25  Praveen-Gurjar
16              15    Sunita-Patil  >

In [48]:
df.info

<bound method DataFrame.info of    First_name Last_name   Age       City            Airline Date_of_Journey  \
0         Ram     Kumar  42.0  BANGALURU             IndiGo      2019-03-24
1       Mohan    Sharma  52.0    CHENNAI          Air India      2019-05-01
2        Tina       Ali  36.0       Pune        Jet Airways      2019-06-09
3       Jeetu    Gandhi   NaN      Delhi             IndiGo      2019-05-12
4       Meera    Kumari   NaN    LUCKNOW             IndiGo      2019-03-01
5         Ram     Kumar  42.0  BANGALURU                NaN      2019-03-24
6       Mohan    Sharma  52.0    CHENNAI                NaN      2019-05-01
7      Rajesh     Pawar  39.0        NaN        Jet Airways      2019-03-01
8      Sanjay     Patil  43.0        NaN        Jet Airways      2019-03-12
9     Trishul    Shinde  45.0       Pune  Multiple carriers      2019-05-27
10     Sameer     Patil  39.0      Delhi        Jet Airways      2019-03-12
11       Amol     Mahul  40.0    LUCKNOW        Jet Airways      2019-03-01
12    Praveen    Gurjar  47.0  BANGALURU        Jet Airways      2019-03-12
13     Sunita     Patil  40.0    CHENNAI  Multiple carriers      2019-05-27
14       Amol     Mahul  40.0    LUCKNOW        Jet Airways      2019-03-01
15    Praveen    Gurjar  47.0  BANGALURU        Jet Airways      2019-03-12
16     Sunita     Patil  40.0    CHENNAI  Multiple carriers      2019-05-27

    Dep_Time Arrival_Time  Dept_Hour  Dept_Minute  Arrival_Hour  \
0   22:20:00     01:10:00         22           20             1
1   05:50:00     13:15:00          5           50            13
2   09:25:00     04:25:00          9           25             4
3   18:05:00     23:30:00         18            5            23
4   16:50:00     21:35:00         16           50            21
5   22:20:00     01:10:00         22           20             1
6   05:50:00     13:15:00          5           50            13
7   05:05:00     08:00:00          5            5             8
8   08:55:00     10:25:00          8           55            10
9   11:25:00     19:15:00         11           25            19
10  10:25:00     18:55:00         10           25            18
11  05:05:00     08:00:00          5            5             8
12  08:55:00     10:25:00          8           55            10
13  11:25:00     19:15:00         11           25            19
14  05:05:00     08:00:00          5            5             8
15  08:55:00     10:25:00          8           55            10
16  11:25:00     19:15:00         11           25            19

    Arrival_Minute       Full Name
0               10       Ram-Kumar
1               15    Mohan-Sharma
2               25        Tina-Ali
3               30    Jeetu-Gandhi
4               35    Meera-Kumari
5               10       Ram-Kumar
6               15    Mohan-Sharma
7                0    Rajesh-Pawar
8               25    Sanjay-Patil
9               15  Trishul-Shinde
10              55    Sameer-Patil
11               0      Amol-Mahul
12              25  Praveen-Gurjar
13              15    Sunita-Patil
14               0      Amol-Mahul
15              25  Praveen-Gurjar
16              15    Sunita-Patil  >

In [49]:
df.columns

Index(['First_name', 'Last_name', 'Age', 'City', 'Airline', 'Date_of_Journey',
       'Dep_Time', 'Arrival_Time', 'Dept_Hour', 'Dept_Minute', 'Arrival_Hour',
       'Arrival_Minute', 'Full Name'],
      dtype='str')

In [50]:
df['Airline'].unique()

<StringArray>
['IndiGo', 'Air India', 'Jet Airways', nan, 'Multiple carriers']
Length: 5, dtype: str

In [51]:
df.value_counts()

First_name  Last_name  Age   City       Airline            Date_of_Journey  Dep_Time  Arrival_Time  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute  Full Name
Amol        Mahul      40.0  LUCKNOW    Jet Airways        2019-03-01       05:05:00  08:00:00      5          5            8             0               Amol-Mahul        2
Praveen     Gurjar     47.0  BANGALURU  Jet Airways        2019-03-12       08:55:00  10:25:00      8          55           10            25              Praveen-Gurjar    2
Sunita      Patil      40.0  CHENNAI    Multiple carriers  2019-05-27       11:25:00  19:15:00      11         25           19            15              Sunita-Patil      2
Ram         Kumar      42.0  BANGALURU  IndiGo             2019-03-24       22:20:00  01:10:00      22         20           1             10              Ram-Kumar         1
Mohan       Sharma     52.0  CHENNAI    Air India          2019-05-01       05:50:00  13:15:00      5          50           13            15              Mohan-Sharma      1
Tina        Ali        36.0  Pune       Jet Airways        2019-06-09       09:25:00  04:25:00      9          25           4             25              Tina-Ali          1
Trishul     Shinde     45.0  Pune       Multiple carriers  2019-05-27       11:25:00  19:15:00      11         25           19            15              Trishul-Shinde    1
Sameer      Patil      39.0  Delhi      Jet Airways        2019-03-12       10:25:00  18:55:00      10         25           18            55              Sameer-Patil      1
Name: count, dtype: int64

In [52]:
# Mean : Avrage Value
# Median : Middle Value
# Mode : Most Frequent
# Nuniquie: Returns all the uniqiue values of data frame 

List1 = [1,2,3,4,5]
Series = pd.Series(List1)
Series.median()

np.float64(3.0)

In [53]:
list1 = [1,2,3,4,5,6,3] 
sereis = pd.Series(list1)
sereis.mean()

np.float64(3.4285714285714284)

In [54]:
df['Airline'].value_counts()
df['Airline'].mode()

0    Jet Airways
Name: Airline, dtype: str

In [55]:
df['Airline'].value_counts()

Airline
Jet Airways          8
IndiGo               3
Multiple carriers    3
Air India            1
Name: count, dtype: int64

In [56]:
df.nunique()

First_name         12
Last_name          10
Age                 8
City                5
Airline             4
Date_of_Journey     7
Dep_Time            9
Arrival_Time        9
Dept_Hour           8
Dept_Minute         5
Arrival_Hour        9
Arrival_Minute      7
Full Name          12
dtype: int64

In [57]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [58]:
#Coloum Filter 
FilterOne = ["city"]
df['City']

0     BANGALURU
1       CHENNAI
2          Pune
3         Delhi
4       LUCKNOW
5     BANGALURU
6       CHENNAI
7           NaN
8           NaN
9          Pune
10        Delhi
11      LUCKNOW
12    BANGALURU
13      CHENNAI
14      LUCKNOW
15    BANGALURU
16      CHENNAI
Name: City, dtype: str

In [59]:
df[0:4]

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi

In [60]:
df[5:8]

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar

In [61]:
df = file_path = "/Users/w.ishal27/Downloads/Small Airline.csv"

In [ ]:
# Row And Column Filtering
# Syntax df.loc[RowIndexNumber,[ColumnNames]]
ColumnList = ['City','Airline']
df = pd.read_csv("/Users/w.ishal27/Desktop/EthansX/Small Airline.csv")
df.loc[0:4, ColumnList]

FileNotFoundError: [Errno 2] No such file or directory: '/Users/w.ishal27/Downloads/Small Airline.csv'

In [ ]:
# df.loc[rowNumbers,[ColumnName]]
df.loc[4:5,['City','Airlines']]

KeyError: "['Airlines'] not in index"